// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJy6FylD_hnxAyVKFvNeFgWL5LH4eklwo',
    appId: '1:720612401099:web:6bb46da0bd4613ff2da04e',
    messagingSenderId: '720612401099',
    projectId: 'reddit-48240',
    authDomain: 'reddit-48240.firebaseapp.com',
    storageBucket: 'reddit-48240.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAffbU_xFDYw-Ko5ZULQ1m8Egz-j3rIWSA',
    appId: '1:720612401099:android:e60671b4a8bc71072da04e',
    messagingSenderId: '720612401099',
    projectId: 'reddit-48240',
    storageBucket: 'reddit-48240.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHhsCdqQT4wNqbr8Ib8mKRovpEJwaes74',
    appId: '1:720612401099:ios:8e0124dd9e8e5c3d2da04e',
    messagingSenderId: '720612401099',
    projectId: 'reddit-48240',
    storageBucket: 'reddit-48240.appspot.com',
    iosClientId: '720612401099-5kkdrtd9c74ub948veudoinnou12vn2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.reddit',
  );
}
